# Generated by Django 5.2 on 2025-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paystack_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='original_email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='original_name',
            field=models.CharField(default='default@example.com', max_length=200),
            preserve_default=False,
        ),
    ]
